"""Add index to order dates

Revision ID: 0003
Revises: 0002
Create Date: 2025-12-30 12:02:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_order_dates', 'orders', ['issue_date', 'planned_completion_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_dates', table_name='orders')
    # ### end Alembic commands ###
