"""Enable pg_trgm and add gin index to work_details

Revision ID: 0005
Revises: 0004
Create Date: 2025-12-30 12:04:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_index(
        'ix_orders_work_details_gin',
        'orders',
        ['work_details'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'work_details': 'jsonb_path_ops'}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_work_details_gin', table_name='orders')
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    # ### end Alembic commands ###
